<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'iPhone 15 Black',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 1,
                'price' => 899.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 6 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 6 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A16 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie 20 W, bezdrôtové nabíjanie 15 W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Blue',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 3,
                'price' => 899.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 6 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 6 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A16 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie 20 W, bezdrôtové nabíjanie 15 W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Pink',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 6,
                'price' => 899.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 6 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 6 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A16 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie 20 W, bezdrôtové nabíjanie 15 W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Green',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 4,
                'price' => 899.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 6 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 6 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A16 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie 20 W, bezdrôtové nabíjanie 15 W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Yellow',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 7,
                'price' => 899.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 6 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 6 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A16 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie 20 W, bezdrôtové nabíjanie 15 W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Pro Natural',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 8,
                'price' => 1099.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED (120Hz), RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179 (120Hz), operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A17 Pro, fotoaparát: 48Mpx (f/1,8) hlavný + 12Mpx širokouhlý + 12Mpx teleobjektív, predná kamera 12Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 15 Pro Blue',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 3,
                'price' => 1099.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED (120Hz), RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179 (120Hz), operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A17 Pro, fotoaparát: 48Mpx (f/1,8) hlavný + 12Mpx širokouhlý + 12Mpx teleobjektív, predná kamera 12Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15W, model 2023, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Black',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 1,
                'price' => 999.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A18 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15 W, batéria 3561 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 White',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 2,
                'price' => 999.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A18 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15 W, batéria 3561 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Blue',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 3,
                'price' => 999.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A18 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15 W, batéria 3561 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Pink',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 6,
                'price' => 999.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A18 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15 W, batéria 3561 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Green',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 4,
                'price' => 999.99,
                'stockquantity' => 99,
                'short_description' => '6,1\" Super Retina XDR OLED, RAM 8 GB, ROM 128 GB',
                'description' => 'Mobilný telefón - 6,1\" Super Retina XDR OLED 2556 x 1179, operačná pamäť 8 GB, vnútorná pamäť 128 GB, single SIM + eSIM, procesor Apple A18 Bionic, fotoaparát: 48 Mpx (f/1,6) hlavný + 12 Mpx širokouhlý, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 15 W, batéria 3561 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Pro Black',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 1,
                'price' => 1199.99,
                'stockquantity' => 99,
                'short_description' => '6,3\" Super Retina XDR OLED (120 Hz), RAM 8 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,3\" Super Retina XDR OLED 2622 x 1206 (120 Hz), operačná pamäť 8 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A18 Pro, fotoaparát: 48 Mpx (f/1,78) hlavný + 48 Mpx širokouhlý + 12 Mpx teleobjektív, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 25 W, batéria 3582 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Pro White',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 2,
                'price' => 1199.99,
                'stockquantity' => 99,
                'short_description' => '6,3\" Super Retina XDR OLED (120 Hz), RAM 8 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,3\" Super Retina XDR OLED 2622 x 1206 (120 Hz), operačná pamäť 8 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A18 Pro, fotoaparát: 48 Mpx (f/1,78) hlavný + 48 Mpx širokouhlý + 12 Mpx teleobjektív, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 25 W, batéria 3582 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Pro Desert',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 7,
                'price' => 1199.99,
                'stockquantity' => 99,
                'short_description' => '6,3\" Super Retina XDR OLED (120 Hz), RAM 8 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,3\" Super Retina XDR OLED 2622 x 1206 (120 Hz), operačná pamäť 8 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A18 Pro, fotoaparát: 48 Mpx (f/1,78) hlavný + 48 Mpx širokouhlý + 12 Mpx teleobjektív, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 25 W, batéria 3582 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPhone 16 Pro Natural',
                'brand_id' => 1,
                'category_id' => 1,
                'color_id' => 8,
                'price' => 1199.99,
                'stockquantity' => 99,
                'short_description' => '6,3\" Super Retina XDR OLED (120 Hz), RAM 8 GB, ROM 256 GB',
                'description' => 'Mobilný telefón - 6,3\" Super Retina XDR OLED 2622 x 1206 (120 Hz), operačná pamäť 8 GB, vnútorná pamäť 256 GB, single SIM + eSIM, procesor Apple A18 Pro, fotoaparát: 48 Mpx (f/1,78) hlavný + 48 Mpx širokouhlý + 12 Mpx teleobjektív, predná kamera 12 Mpx, GPS, NFC, LTE, 5G, USB-C, vodoodolný podľa IP68, rýchle nabíjanie, bezdrôtové nabíjanie 25 W, batéria 3582 mAh, model 2024, iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Air M4 Midnight',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 1,
                'price' => 1459.99,
                'stockquantity' => 99,
                'short_description' => 'M4 (10-jadrový), 15,3\" IPS lesklý, RAM 16 GB, SSD 256 GB',
                'description' => 'MacBook - Apple M4 (10-jadrový), 15,3\" IPS lesklý 2880 x 1864 px, RAM 16 GB, Apple M4 10-jadrová GPU, SSD 256 GB podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6E, Bluetooth, hmotnosť 1,51 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Air M4 Silver',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 8,
                'price' => 1459.99,
                'stockquantity' => 99,
                'short_description' => 'M4 (10-jadrový), 15,3\" IPS lesklý, RAM 16 GB, SSD 256 GB',
                'description' => 'MacBook - Apple M4 (10-jadrový), 15,3\" IPS lesklý 2880 x 1864 px, RAM 16 GB, Apple M4 10-jadrová GPU, SSD 256 GB podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6E, Bluetooth, hmotnosť 1,51 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Air M4 Sky Blue',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 3,
                'price' => 1459.99,
                'stockquantity' => 99,
                'short_description' => 'M4 (10-jadrový), 15,3\" IPS lesklý, RAM 16 GB, SSD 256 GB',
                'description' => 'MacBook - Apple M4 (10-jadrový), 15,3\" IPS lesklý 2880 x 1864 px, RAM 16 GB, Apple M4 10-jadrová GPU, SSD 256 GB podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6E, Bluetooth, hmotnosť 1,51 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Air M4 Starlight',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 7,
                'price' => 1459.99,
                'stockquantity' => 99,
                'short_description' => 'M4 (10-jadrový), 15,3\" IPS lesklý, RAM 16 GB, SSD 256 GB',
                'description' => 'MacBook - Apple M4 (10-jadrový), 15,3\" IPS lesklý 2880 x 1864 px, RAM 16 GB, Apple M4 10-jadrová GPU, SSD 256 GB podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6E, Bluetooth, hmotnosť 1,51 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Pro M4 Black',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 1,
                'price' => 2899.99,
                'stockquantity' => 99,
                'short_description' => 'M4 Pro (14-jadrový), 16,2\" Liquid Retina XDR, 120 Hz, RAM 24 GB, SSD 512 GB',
                'description' => '  MacBook - Apple M4 Pro (14-jadrový), 16,2\" Liquid Retina XDR lesklý 3456 x 2234 px, 120 Hz, RAM 24 GB, Apple M4 PRO 20-jadrová GPU, SSD 512 GB, podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6, WiFi, Bluetooth, hmotnosť 2,14 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macbook Pro M4 Silver',
                'brand_id' => 1,
                'category_id' => 2,
                'color_id' => 8,
                'price' => 2899.99,
                'stockquantity' => 99,
                'short_description' => 'M4 Pro (14-jadrový), 16,2\" Liquid Retina XDR, 120 Hz, RAM 24 GB, SSD 512 GB',
                'description' => '  MacBook - Apple M4 Pro (14-jadrový), 16,2\" Liquid Retina XDR lesklý 3456 x 2234 px, 120 Hz, RAM 24 GB, Apple M4 PRO 20-jadrová GPU, SSD 512 GB, podsvietená klávesnica, webkamera, čítačka odtlačkov prstov, WiFi 6, WiFi, Bluetooth, hmotnosť 2,14 kg, macOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad 2025 Silver',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 8,
                'price' => 419.99,
                'stockquantity' => 99,
                'short_description' => '10,9\" QHD Liquid Retina, A16 Bionic, RAM 6 GB, ROM 128 GB',
                'description' => 'Tablet - displej 10,9\" QHD 2360 x 1640 Liquid Retina, Apple A16 Bionic, RAM 6 GB, kapacita úložiska 128 GB, WiFi, Bluetooth, GPS, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, batéria 28,93 mAh, iPadOS 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad 2025 Blue',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 3,
                'price' => 419.99,
                'stockquantity' => 99,
                'short_description' => '10,9\" QHD Liquid Retina, A16 Bionic, RAM 6 GB, ROM 128 GB',
                'description' => 'Tablet - displej 10,9\" QHD 2360 x 1640 Liquid Retina, Apple A16 Bionic, RAM 6 GB, kapacita úložiska 128 GB, WiFi, Bluetooth, GPS, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, batéria 28,93 mAh, iPadOS 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad 2025 Pink',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 6,
                'price' => 419.99,
                'stockquantity' => 99,
                'short_description' => '10,9\" QHD Liquid Retina, A16 Bionic, RAM 6 GB, ROM 128 GB',
                'description' => 'Tablet - displej 10,9\" QHD 2360 x 1640 Liquid Retina, Apple A16 Bionic, RAM 6 GB, kapacita úložiska 128 GB, WiFi, Bluetooth, GPS, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, batéria 28,93 mAh, iPadOS 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad 2025 Yellow',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 7,
                'price' => 419.99,
                'stockquantity' => 99,
                'short_description' => '10,9\" QHD Liquid Retina, A16 Bionic, RAM 6 GB, ROM 128 GB',
                'description' => 'Tablet - displej 10,9\" QHD 2360 x 1640 Liquid Retina, Apple A16 Bionic, RAM 6 GB, kapacita úložiska 128 GB, WiFi, Bluetooth, GPS, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, batéria 28,93 mAh, iPadOS 18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad Pro 2024 Silver',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 8,
                'price' => 1249.99,
                'stockquantity' => 99,
                'short_description' => '11\" QHD Ultra Retina XDR, M4 s 10-jadrovou GPU, RAM 8 GB, ROM 256 GB',
                'description' => 'Tablet - displej 11\" QHD 2420 x 1668 Ultra Retina XDR, Apple M4 s 10-jadrovou GPU, RAM 8 GB, kapacita úložiska 256 GB, WiFi, Bluetooth, NFC, OTG, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, iPadOS 17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad Pro 2024 Black',
                'brand_id' => 1,
                'category_id' => 3,
                'color_id' => 1,
                'price' => 1249.99,
                'stockquantity' => 99,
                'short_description' => '11\" QHD Ultra Retina XDR, M4 s 10-jadrovou GPU, RAM 8 GB, ROM 256 GB',
                'description' => 'Tablet - displej 11\" QHD 2420 x 1668 Ultra Retina XDR, Apple M4 s 10-jadrovou GPU, RAM 8 GB, kapacita úložiska 256 GB, WiFi, Bluetooth, NFC, OTG, bez podpory (iba WiFi), zadný fotoaparát 12 Mpx (f/1,8), predný fotoaparát 12 Mpx (f/2,4), USB-C, iPadOS 17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods 4',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, IP54, výdrž batérie až 30 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, True Wireless, kôstky, otvorená konštrukcia, Bluetooth 5.3, prepínanie skladieb, prijímanie hovorov, certifikácia IP54, výdrž batérie až 30 h (5 h+30 h)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods 4 s ANC',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 179.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, aktívne potlačenie hluku, výdrž batérie až 30 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, True Wireless, kôstky, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.3, Ambient sound, Hi-Res audio, hlasový asistent, prepínanie skladieb, prijímanie hovorov, certifikácia IP54, frekvenčný rozsah 20-20000 Hz, výdrž batérie až 30 h (5 h+25 h)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods 3',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 162.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, Bluetooth 5.0, certifikácia IPX4',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, kôstky, Bluetooth 5.0, prepínanie skladieb, prijímanie hovorov, certifikácia IPX4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Pro 2',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 259.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, aktívne potlačenie hluku, výdrž batérie až 30 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, True Wireless, štuple, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.3, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, certifikácia IP54, výdrž batérie až 30 h (6 h+24 h)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Max Blue',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 3,
                'price' => 559.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, aktívne potlačenie hluku, výdrž batérie až 20 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, okolo uší, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.0, Ambient sound, Hi-Res audio, hlasový asistent, priestorový zvuk 7.1, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, menič 40 mm, výdrž batérie až 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Max Purple',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 9,
                'price' => 559.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, aktívne potlačenie hluku, výdrž batérie až 20 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, okolo uší, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.0, Ambient sound, Hi-Res audio, hlasový asistent, priestorový zvuk 7.1, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, menič 40 mm, výdrž batérie až 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Max Midnight',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 559.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, aktívne potlačenie hluku, výdrž batérie až 20 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, okolo uší, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.0, Ambient sound, Hi-Res audio, hlasový asistent, priestorový zvuk 7.1, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, menič 40 mm, výdrž batérie až 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Max Starlight',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 7,
                'price' => 559.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, aktívne potlačenie hluku, výdrž batérie až 20 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, okolo uší, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.0, Ambient sound, Hi-Res audio, hlasový asistent, priestorový zvuk 7.1, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, menič 40 mm, výdrž batérie až 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AirPods Max Orange',
                'brand_id' => 1,
                'category_id' => 4,
                'color_id' => 5,
                'price' => 559.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, aktívne potlačenie hluku, výdrž batérie až 20 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, okolo uší, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.0, Ambient sound, Hi-Res audio, hlasový asistent, priestorový zvuk 7.1, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, menič 40 mm, výdrž batérie až 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Major IV',
                'brand_id' => 2,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 75.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, 3,5 mm Jack, Bluetooth, výdrž batérie až 80 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, na uši, uzatvorená konštrukcia, 3,5 mm Jack, Bluetooth 5.0, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, frekvenčný rozsah 20-20000 Hz, citlivosť 99 dB/mW, impedancia 32 Ohm, menič 40 mm, odnímateľný kábel 1,5 m, výdrž batérie až 80 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Major V Black',
                'brand_id' => 2,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 149.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, Bluetooth 5.3, výdrž batérie až 100 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, na uši, polouzatvorená konštrukcia, Bluetooth 5.3, podpora SBC, prijímanie hovorov, frekvenčný rozsah 20-20000 Hz, citlivosť 99 dB/mW, impedancia 32 Ohm, výdrž batérie až 100 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Major V Brown',
                'brand_id' => 2,
                'category_id' => 4,
                'color_id' => 10,
                'price' => 149.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, Bluetooth 5.3, výdrž batérie až 100 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, na uši, polouzatvorená konštrukcia, Bluetooth 5.3, podpora SBC, prijímanie hovorov, frekvenčný rozsah 20-20000 Hz, citlivosť 99 dB/mW, impedancia 32 Ohm, výdrž batérie až 100 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Major V Cream',
                'brand_id' => 2,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 149.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, cez hlavu, Bluetooth 5.3, výdrž batérie až 100 h',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, cez hlavu, na uši, polouzatvorená konštrukcia, Bluetooth 5.3, podpora SBC, prijímanie hovorov, frekvenčný rozsah 20-20000 Hz, citlivosť 99 dB/mW, impedancia 32 Ohm, výdrž batérie až 100 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Motif II',
                'brand_id' => 2,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 137.99,
                'stockquantity' => 99,
                'short_description' => 'Bezdrôtové slúchadlá, True Wireless, aktívne potlačenie hluku, Bluetooth 5.3, IPX5',
                'description' => 'Bezdrôtové slúchadlá - s mikrofónom, True Wireless, štuple, aktívne potlačenie hluku (ANC), uzatvorená konštrukcia, Bluetooth 5.3, podpora SBC, prepínanie skladieb, prijímanie hovorov, s ovládaním hlasitosti, certifikácia IPX5, frekvenčný rozsah 20-20000 Hz, citlivosť 108 dB/mW, impedancia 16 Ohm, výdrž batérie až 9 h (9 h+43 h)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Go 2 Black',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 34.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 3,1 W, Bluetooth 4.2, certifikácia IP67, výdrž batérie 5 h',
                'description' => 'Bluetooth reproduktor - s výkonom 3,1 W, k mobilu, frekvenčný rozsah od 180 Hz do 20000 Hz, Bluetooth 4.2, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 5 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Go 2 Blue',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 3,
                'price' => 34.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 3,1 W, Bluetooth 4.2, certifikácia IP67, výdrž batérie 5 h',
                'description' => 'Bluetooth reproduktor - s výkonom 3,1 W, k mobilu, frekvenčný rozsah od 180 Hz do 20000 Hz, Bluetooth 4.2, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 5 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Go 2 Red',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 5,
                'price' => 34.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 3,1 W, Bluetooth 4.2, certifikácia IP67, výdrž batérie 5 h',
                'description' => 'Bluetooth reproduktor - s výkonom 3,1 W, k mobilu, frekvenčný rozsah od 180 Hz do 20000 Hz, Bluetooth 4.2, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 5 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Flip Essential',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 8,
                'price' => 79.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 20 W, Bluetooth 5.1, certifikácia IPX7, výdrž batérie 10 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 20 W, k mobilu, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IPX7, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 10 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 White',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 2,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Green',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 4,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Blue',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 3,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Red',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 5,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Pink',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 6,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Gray',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 8,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Charge 5 Black',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 143.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 40 W, Bluetooth 5.1, certifikácia IP67, výdrž batérie 20 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 40 W, k mobilu, s USB napájaním, frekvenčný rozsah od 65 Hz do 20000 Hz, Bluetooth 5.1, certifikácia IP67, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 20 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Partybox 120',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 359.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 160 W, Bluetooth 5.4, certifikácia IPX4, výdrž batérie 12 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 160 W, párty, s prehrávaním USB flash, frekvenčný rozsah od 40 Hz do 20000 Hz, AUX, Bluetooth 5.4, certifikácia IPX4, podpora FLAC a mp3, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 12 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Partybox 320',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 599.99,
                'stockquantity' => 99,
                'short_description' => 'Výkon 240 W, Bluetooth 5.4, certifikácia IPX4, výdrž batérie 18 h',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 240 W, párty, s prehrávaním USB flash, frekvenčný rozsah od 40 Hz do 20000 Hz, AUX, Bluetooth 5.4, certifikácia IPX4, podpora FLAC a mp3, ovládanie cez zariadenia s OS iOS alebo Android, výdrž batérie 18 h',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Partybox 710',
                'brand_id' => 3,
                'category_id' => 4,
                'color_id' => 1,
                'price' => 799.99,
                'stockquantity' => 99,
                'short_description' => 'Výkonom 800 W, Bluetooth 5.1, certifikácia IPX4',
                'description' => 'Bluetooth reproduktor - aktívny, s výkonom 800 W, k mobilu a párty, s prehrávaním USB flash, s USB napájaním, frekvenčný rozsah od 35 Hz do 20000 Hz, 3,5 mm Jack, Bluetooth 5.1, certifikácia IPX4, ovládanie cez zariadenia s OS iOS alebo Android',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
